app/Http/routes.php
<?php

//Route::group(['domain' => 'subdomain.payroll.app'], function () {
//    Route::get('/', function () {
//        return view('welcome');
//    });
//    Route::get('/me', function (CoinageCalculator $calculator) {
////        abort(400, 'hrhryyuy');
//        return response('hege', 400);
//        $values = [1000,500,200,100,50,40,20,10,5,1];
//        dd($calculator->withAmount(68489019)->withDivisions($values)->get());
////        $amount = 68489019;
////        $thousands = explode('.', $amount / 1000);
////        $fiveHundreds = explode('.', $thousands[1] / 500);
//
////        var_dump('Total:' . number_format($amount, 2));
//        dd(getAmount($amount, $values));
//    });
//});
//
//function getAmount($amount, $value, $step = 0, $coinage = [])
//{
//    $result = explode('.', $amount / $value[$step]);
//    $remainder = $amount - ($value[$step] * $result[0]);
//    $coinage [] = [
//        $value[$step] => $result[0]
//    ];
//
//    $step++;
//    if ($step < count($value)) {
//        return getAmount($remainder, $value, $step, $coinage);
//    }
//
//    return $coinage;
//}


Route::group(['middleware' => ['auth']], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => function () {
        return view('modules.dashboard');
    }]);
    Route::get('logout', ['as' => 'logout', 'uses' => 'Authentication\AuthController@logout']);
    Route::get('user-profile', ['as' => 'user.profile', 'uses' => 'UsersController@profile']);
    Route::post('user-profile', ['as' => 'user.profile.update', 'uses' => 'UsersController@postProfile']);
    Route::resource('profile', 'CompanyProfileController');
    Route::resource('departments', 'DepartmentsController');
    Route::get('department-print/{department}', ['as' => 'departments.generate', 'uses' => 'DepartmentsController@generate']);
    Route::post('department-print', ['as' => 'departments.pdfs', 'uses' => 'DepartmentsController@getPDF']);
    Route::resource('allowances', 'AllowancesController');
    Route::resource('employee-allowances', 'EmployeeAllowancesController');
    Route::get('allowances-print/{id}', ['as' => 'allowances.generate', 'uses' => 'AllowancesController@generate']);
    Route::post('allowances-print', ['as' => 'allowances.document', 'uses' => 'AllowancesController@getDocument']);
    Route::resource('deductions', 'DeductionsController');
    Route::resource('employee-deductions', 'EmployeeDeductionsController');
    Route::get('deductions-report/{id}', ['as' => 'deductions.report', 'uses' => 'DeductionsController@report']);
    Route::post('deductions-print/{id}', ['as' => 'deductions.generate', 'uses' => 'DeductionsController@generate']);
    Route::post('deductions-print', ['as' => 'deductions.document', 'uses' => 'DeductionsController@getDocument']);
    Route::resource('reliefs', 'ReliefController');
    Route::resource('employee-types', 'EmployeeTypesController');
    Route::resource('payment-methods', 'PaymentMethodsController');
    Route::resource('payment-structures', 'PaymentStructureController');
    Route::resource('shifts', 'ShiftsController');
    Route::resource('work-plans', 'WorkPlanController');
    Route::resource('grades', 'PayGradesController');
    Route::resource('holidays', 'HolidaysController');
    Route::resource('employees', 'EmployeesController');
    Route::resource('contracts', 'EmployeeContractsController');
    Route::resource('assignments', 'EmployeeAssignmentsController');
    Route::resource('employee-payment-methods', 'EmployeePaymentMethodsController');
    Route::resource('payroll', 'PayrollController');
    Route::get('finalize-payroll', 'PayrollController@finalize');
    Route::get('payroll-pdf/{id}', ['as' => 'payroll.pdf', 'uses' => 'PayrollController@getPDF']);
    Route::get('payroll-pdfs', ['as' => 'payroll.pdfs', 'uses' => 'PayrollController@getAllPDFs']);
    Route::get('payroll-view/{month}', ['as' => 'payroll.show.all', 'uses' => 'PayrollController@viewAll']);
    Route::get('payroll-report', ['as' => 'payroll.report', 'uses' => 'PayrollController@report']);
    Route::post('payroll-generate', ['as' => 'payroll.generate', 'uses' => 'PayrollController@generate']);
    Route::post('payroll-print', ['as' => 'payroll.document', 'uses' => 'PayrollController@getDocument']);
    Route::resource('advances', 'AdvancesController');
    Route::get('advances-bulk', ['as' => 'advances.bulk', 'uses' => 'AdvancesController@bulkAssign']);
    Route::post('advances-bulk', ['as' => 'advances.process', 'uses' => 'AdvancesController@bulkProcess']);
    Route::get('loans/details/{loanId}', ['as' => 'loans.details', 'uses' => 'LoansController@details']);
    Route::resource('loans', 'LoansController');
    Route::resource('policies', 'PoliciesController');
//    Route::resource('tax', 'TaxReportsController');
    Route::get('tax', ['as' => 'tax.index', 'uses' => 'TaxReportsController@index']);
    Route::get('tax-report', 'TaxReportsController@getYear');
    Route::post('tax/{type}', ['as' => 'tax.show', 'uses' => 'TaxReportsController@getReport']);
    Route::resource('template', 'ReportTemplateController');
    Route::resource('worked', 'DaysWorkedController');
    Route::resource('hours-worked', 'HoursWorkedController');
    Route::resource('units-made', 'UnitsMadeController');
    Route::resource('coinage', 'CoinageController');
    Route::resource('users', 'UsersController');
    Route::resource('overtime','OvertimeController');
    Route::resource('overtimeaward', 'OvertimeAwardController');
    Route::get('fakers','FakeController@fakers');
});


Route::get('login', ['as' => 'login.index', 'uses' => 'Authentication\AuthController@getLogin']);
Route::post('login', ['as' => 'login.store', 'uses' => 'Authentication\AuthController@postLogin']);
Route::get('forgot', ['as' => 'forgot.index', 'uses' => 'Authentication\AuthController@index']);
Route::post('forgot', ['as' => 'forgot.store', 'uses' => 'Authentication\AuthController@index']);

app/OvertimeAward.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class OvertimeAward extends Model
{
    //
}

app/Http/Controllers/OvertimeAwardController.php
<?php

namespace App\Http\Controllers;

use App\Overtime;
use App\OvertimeAward;
use App\OvertimeSlab;
use Carbon\Carbon;
use Illuminate\Http\Request;

use App\Http\Requests;
use Payroll\Models\EmployeeContract;
use Payroll\Models\Holiday;
use Payroll\Models\Policy;
use Payroll\Parsers\ModelFilter;
use Payroll\Models\Employee;
use Payroll\Parsers\BulkAssigner;
use Payroll\Factories\HTMLElementsFactory;
use Illuminate\Support\Str;

class OvertimeAwardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    const FIELD_NAME = 'time_hours';

    public function index()
    {
        $overtimes = OvertimeAward::orderBy('ot_date','desc')->get()->unique('ot_date');
//        dd($overtimes);
        return view('modules.payroll.overtimeaward.index',compact('overtimes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(BulkAssigner $assigner)
    {

        $requiredFields [] = [
            'name' => 'time_hours',
            'type' => HTMLElementsFactory::TEXT
        ];


//        //$holidays = Holiday::all();
    $allemployees = collect(Employee::all());
        $rows = $allemployees->each(function ($item, $key) use ($allemployees) {
            $allemployees[$key] = collect($item)->only([
                'id', 'payroll_number', 'first_name', 'last_name', 'identification_number'
            ]);
        })->toArray();

$columns = $allemployees->each(function ($item, $key) use ($allemployees) {
    $allemployees[$key] = collect($item)->only([
        'payroll_number', 'first_name', 'last_name', 'identification_number'
    ]);
})->first()->keys()->toArray();
//    dd($columns);
       // dd($requiredFields);

       return view('modules.payroll.overtimeaward.create')
           ->with('rows',$rows)
           ->with('columns',$columns)
           ->with('requiredFields',$requiredFields)
           ->with('formAction',route('overtimeaward.index'))
           ->with('allowCopy',$allowCopy = false)
           ->with('assignToId',Carbon::now());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store()
    {


        $overtimeCollect = collect(request()->all());
        $filterData = $overtimeCollect->filter(function($value, $key){
            return Str::startsWith($key, 'time_hours') && $value != '';
        });

        foreach ($filterData as $key => $value) {
            $insert [] = [
                'employee_id' => substr($key, strlen('time_hours')),
                'ot' => $value,
                'ot_cash' =>$this->getOtcash($overtimeCollect['ot_date'],$value,substr($key, strlen('time_hours'))),
                'ot_date' => $overtimeCollect['ot_date'],
                'ot_status' => 'Unpaid',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ];
        }
//        dd($insert);
        OvertimeAward::insert($insert);
    }

    public function getOtcash($dateSelected,$hours,$employee)
    {
        $getHoliday = Holiday::all()->toArray();

        $arrayValue = count($getHoliday);
        if (($arrayValue == 0) && $dateSelected != Carbon::parse($dateSelected)->isWeekend()) {
            //this is standard

            return ($this->calculateOT($hours,$rate='rate',$employee));
        }

        elseif(($arrayValue == 0) && $dateSelected == Carbon::parse($dateSelected)->isWeekend()) {
            //special
            return ($this->calculateOT($hours,$rate='slab',$employee));


        }
        else{
            foreach ($getHoliday as $holiday) {
                $date = $holiday['holiday_day'] . '-' . $holiday['holiday_month'] . '-' . Carbon::now()->year;
                if ($dateSelected != $date && $dateSelected != Carbon::parse($dateSelected)->isWeekend()) {
                    return ($this->calculateOT($hours,$rate='slab',$employee));
                }
//                dd('got you');
            }
        }

    }

    public function calculateOT($hours,$rate,$employee)
    {//find employee
        $salary = EmployeeContract::where('employee_id',$employee)->get();
        $theEmployeeSalary = $salary->each(function ($item, $key) use ($salary){
            $salary[$key] = collect($item)->only(['current_basic_salary']);
        })->first();
        //company days
        $numberDays= Policy::where('module_id',29)->get();
        $days = $numberDays->each(function ($item, $key) use ($numberDays) {
            $numberDays[$key] = collect($item)->only([
                'value'
            ]);
        })->last();
        //slary per hr
        $employSalary = ($theEmployeeSalary['current_basic_salary']/ $days['value']);
//overtime type
        $otType = Overtime::where('type',$rate)->get();
        $rowrate = $otType->each(function ($item, $key) use ($otType) {
            $otType[$key] = collect($item)->only([
                'id','type', 'rate'
            ]);
        })->toArray();
        foreach($rowrate as $rate){
            if($rate['type'] == 'rate'){
                $money = $this->calculateRate($hours,$rate['rate'],$employSalary);

                return $money;
            }

            else {
                $rows = OvertimeSlab::all()->where('overtime_id', $rate['id'])->toArray();
                $i = count($rows) + 1;
                return $this->calculateSlab($hours,$employSalary,$rate['id'],$i,$rows,$total = 0);
            }
        }

    }

    public function calculateRate($hours, $sendRate,$employSalary)
    {

        return (number_format(($hours*$sendRate*$employSalary),2));
    }

    public function calculateSlab($hours,$employSalary,$id,$i,$rows,$total)
    {$otslabs = collect($rows)->each(function($item, $key) use($rows){
        $rows[$key] = collect($item)->only(['min_time','max_time','rate']);
    })->toArray();
        foreach($otslabs as $otslab){
            $time = ($otslab['max_time']-$otslab['min_time'])+1;
            if(is_array($otslab) && ($hours > $time && $hours != $time)){
                $hours = $hours - $time;
                $total = $total + ($employSalary*$time * $otslab['rate']);

            }
            else {
                $total = $total + ($employSalary * $hours * $otslab['rate']);
//                echo $total . ' ' . $hours . $otslab['rate'] ;
                return $total;
            }

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (count(explode('-', $id)) > 1) {
            $overtimeawardsarray = OvertimeAward::where('ot_date', '<=', Carbon::parse('1-'. $id)->endOfMonth()->format('d-m-Y'))
                ->get()->toArray();
            foreach($overtimeawardsarray as $key => $ota){
                $overtimeawards [] = [
                    'id' =>$ota['id'],
                    'employee_id' => $ota['employee_id'],
                    'first_name' => $this->getEmployee($ota['employee_id'],$rq = 'first_name'),
                    'last_name' => $this->getEmployee($ota['employee_id'],$rq = 'last_name'),
                    'payroll' => $this->getEmployee($ota['employee_id'],$rq = 'payroll'),
                    'ot_cash' => $ota['ot_cash'],
                    'ot_status' => $ota['ot_status'],
                    'ot_date' => $ota['ot_date']

                ];
            }
//dd($overtimeawardsarray);
            return view('modules.payroll.overtimeaward.show')
                ->withTitle(Carbon::parse('30-' . $id)->format('F Y'))
                ->withOvertimeawards($overtimeawards);
        }

        $advances = $advance
            ->where('for_month', '>=', Carbon::parse('01-01-' . $id)->format('Y-m-d'))
            ->where('for_month', '<=', Carbon::parse('31-12-' . $id)->format('Y-m-d'))
            ->get();

        return view('modules.payroll.advances.show')
            ->withTitle(Carbon::parse('01-01-' . $id)->format('Y'))
            ->withAdvances($advances);
    }

    public function getEmployee($id,$requetdata)
    {
        $employee = Employee::select('payroll_number','first_name','last_name')->where('id',$id)->get()->toArray();
        foreach($employee as $name)
        {
            $firstname = $name['first_name'];
            $lastname = $name['last_name'];
            $payroll = $name['payroll_number'];
            if($requetdata == 'first_name')
            {
                return $firstname;
            }if($requetdata == 'last_name')
            {
                return $lastname;
            }else
            {
                return $payroll;
            }

        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/modules/payroll/overtimeaward/index.blade.php
@extends('layout')

@section('content')
    <div class="page-head">
        <div class="page-title">
            {{--<h1>Salary Advances - <small></small></h1>--}}
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            {{--<a href="{{ route('advances.index') }}">Salary Advances</a>--}}
        </li>
    </ul>

    <div class="row">
        <div class="col-sm-12">
            <!-- BEGIN PORTLET-->
            <div class="portlet light ">
                <div class="portlet-title">
                    <div class="caption caption-md">
                        <i class="icon-bar-chart theme-font-color hide"></i>
                        <span class="caption-subject theme-font-color bold uppercase">Current Salary Advances</span>
                    </div>
                    <div class="actions">
                        {{--<a href="{{ route('advances.create') }}" class="btn btn-transparent grey-salsa btn-circle btn-sm active"><i class="fa fa-plus"></i> Process New Advance</a>--}}
                        {{--<a href="{{ route('advances.bulk') }}" class="btn btn-transparent grey-salsa btn-circle btn-sm active"><i class="fa fa-plus"></i> Process Bulk Advances</a>--}}
                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-hover table-responsive dataTable" id="allowances_table">
                        <thead>
                        <tr>
                            <th width="20">#</th>
                            <th>
                                Month
                            </th>
                            <th>
                                Year
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $x = 0; ?>
                        @foreach($overtimes as $overtime)
                            <?php $x++; ?>
                            <tr>
                                <td class="text-right">{{ $x }}</td>
                                <td>
                                    <a href="{{ route('overtimeaward.show', \Carbon\Carbon::parse($overtime->ot_date)->format('m-Y')) }}">
                                        {{ \Carbon\Carbon::parse($overtime->ot_date)->format('F') }}
                                    </a>
                                </td>
                                <td>
                                    <a href="{{ route('overtimeaward.show', \Carbon\Carbon::parse($overtime->ot_date)->format('Y')) }}">
                                        {{ \Carbon\Carbon::parse($overtime->ot_date)->format('Y') }}
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END PORTLET-->
        </div>
    </div>

@endsection

resources/views/modules/payroll/overtimeaward/show.blade.php
@extends('layout')

@section('content')
    <div class="page-head">
        <div class="page-title">
            <h1>Salary Advances - <small> Current advances given to employees in the Organization</small></h1>
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
{{--            <a href="{{ route('advances.index') }}">Salary Advances</a>--}}
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">Salary Advances for {{ $title }}</a>
        </li>
    </ul>

    <div class="row">
        <div class="col-sm-12">
            <!-- BEGIN PORTLET-->
            <div class="portlet light ">
                <div class="portlet-title">
                    <div class="caption caption-md">
                        {{--<a href="{{ route('advances.index') }}" class="btn btn-transparent grey-salsa btn-circle btn-sm active"><i class="fa fa-angle-left"></i> back</a>--}}
                        <i class="icon-bar-chart theme-font-color hide"></i>
                        <span class="caption-subject theme-font-color bold uppercase">Current Salary Advances for {{ $title }}</span>
                    </div>
                    <div class="actions">
                        {{--<a href="{{ route('advances.create') }}" class="btn btn-transparent grey-salsa btn-circle btn-sm active"><i class="fa fa-plus"></i> Process New Payment</a>--}}
                        {{--<a href="{{ route('advances.create') }}" class="btn btn-transparent grey-salsa btn-circle btn-sm active"><i class="fa fa-plus"></i> Process New Advance</a>--}}
                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-hover table-responsive dataTable" id="allowances_table">
                        <thead>
                        <tr>
                            <th>
                                Advance For
                            </th>
                            <th>
                                Payroll Number
                            </th>
                            <th>
                                Employee Name
                            </th>
                            <th>
                                Amount
                            </th>
                            <th>
                                Status
                            </th>
                            <th>
                                Edit
                            </th>
                            <th>
                                Delete
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($overtimeawards as $overtimeaward)
                            <tr>
                                <td>
                                    {{ \Carbon\Carbon::parse($overtimeaward['ot_date'])->format('F Y') }}
                                </td>
                                <td>
                                    <a href="{{ route('employees.show', $overtimeaward['employee_id']) }}">{{ $overtimeaward['payroll'] }}</a>
                                </td>
                                <td>
                                    <a href="{{ route('employees.show', $overtimeaward['employee_id']) }}">{{ $overtimeaward['first_name'] . ' ' . $overtimeaward['last_name'] }}</a>
                                </td>
                                <td>
                                    {{ $overtimeaward['ot_cash'] }}
                                </td>
                                <td>
                                    {{ $overtimeaward['ot_status'] }}
                                </td>
                                <td>
                                    <a class="btn btn-success btn-xs" href="{{ route('overtimeaward.edit', $overtimeaward['id']) }}">
                                        Edit </a>
                                </td>
                                <td>
                                    <a href="{{ route('overtimeaward.destroy', $overtimeaward['id']) }}" class="btn btn-danger btn-xs" data-method="delete" rel="nofollow" data-confirm="Are you sure you want to delete this?" data-token="{{ csrf_token() }}">Delete</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END PORTLET-->
        </div>
    </div>

@endsection